#ifndef SGFRAMEWORK_GLOBAL_H
#define SGFRAMEWORK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SGFRAMEWORK_LIBRARY)
#  define SGFRAMEWORKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SGFRAMEWORKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SGFRAMEWORK_GLOBAL_H
