#-------------------------------------------------
#
# Project created by QtCreator 2014-09-08T15:09:36
#
#-------------------------------------------------

QT       += gui

TARGET = PhysicPackage
TEMPLATE = lib
CONFIG += staticlib

INCLUDEPATH+= BulletPhysics

SOURCES += \
    physics/boundingbox.cpp \
    physics/boundingsphere.cpp \
    physics/dynamiccharacter.cpp \
    physics/dynamiccharacterwithcam.cpp \
    physics/physicengine.cpp \
    physics/physicenginemanager.cpp \
    physics/physicobject.cpp \
    physics/trigger.cpp \
    physics/PhysicMath/eigenvector.cpp \
    physics/BulletPhysicEngine/bulletcollisiondispatcher.cpp \
    physics/BulletPhysicEngine/bulletdebugdrawer.cpp \
    physics/BulletPhysicEngine/bulletdiscretedynamicsworld.cpp \
    physics/BulletPhysicEngine/bulletdynamiccharacter.cpp \
    physics/BulletPhysicEngine/bulletdynamiccharacterwithcam.cpp \
    physics/BulletPhysicEngine/bulletparallelcollisioncallback.cpp \
    physics/BulletPhysicEngine/bulletphysicengine.cpp \
    physics/BulletPhysicEngine/bulletphysicmatrixtogeometry.cpp \
    physics/BulletPhysicEngine/bulletphysicobject.cpp \
    physics/BulletPhysicEngine/bulletspucollisiondispatcher.cpp

SOURCES += BulletPhysics/BulletCollision/BroadphaseCollision/btAxisSweep3.cpp \
    BulletPhysics/BulletCollision/BroadphaseCollision/btBroadphaseProxy.cpp \
    BulletPhysics/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp \
    BulletPhysics/BulletCollision/BroadphaseCollision/btDbvt.cpp \
    BulletPhysics/BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp \
    BulletPhysics/BulletCollision/BroadphaseCollision/btDispatcher.cpp \
    BulletPhysics/BulletCollision/BroadphaseCollision/btMultiSapBroadphase.cpp \
    BulletPhysics/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp \
    BulletPhysics/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp \
    BulletPhysics/BulletCollision/BroadphaseCollision/btSimpleBroadphase.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btBoxBoxDetector.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btCollisionObject.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btCollisionWorld.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btGhostObject.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btManifoldResult.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btSimulationIslandManager.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/btUnionFind.cpp \
    BulletPhysics/BulletCollision/CollisionDispatch/SphereTriangleDetector.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btBox2dShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btBoxShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btCapsuleShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btCollisionShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btCompoundShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btConcaveShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btConeShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btConvex2dShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btConvexHullShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btConvexInternalShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btConvexPointCloudShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btConvexPolyhedron.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btConvexShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btCylinderShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btEmptyShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btMinkowskiSumShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btMultiSphereShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btOptimizedBvh.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btPolyhedralConvexShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btShapeHull.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btSphereShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btStaticPlaneShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btStridingMeshInterface.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btTetrahedronShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btTriangleBuffer.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btTriangleCallback.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btTriangleMesh.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btTriangleMeshShape.cpp \
    BulletPhysics/BulletCollision/CollisionShapes/btUniformScalingShape.cpp \
    BulletPhysics/BulletCollision/Gimpact/btContactProcessing.cpp \
    BulletPhysics/BulletCollision/Gimpact/btGenericPoolAllocator.cpp \
    BulletPhysics/BulletCollision/Gimpact/btGImpactBvh.cpp \
    BulletPhysics/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.cpp \
    BulletPhysics/BulletCollision/Gimpact/btGImpactQuantizedBvh.cpp \
    BulletPhysics/BulletCollision/Gimpact/btGImpactShape.cpp \
    BulletPhysics/BulletCollision/Gimpact/btTriangleShapeEx.cpp \
    BulletPhysics/BulletCollision/Gimpact/gim_box_set.cpp \
    BulletPhysics/BulletCollision/Gimpact/gim_contact.cpp \
    BulletPhysics/BulletCollision/Gimpact/gim_memory.cpp \
    BulletPhysics/BulletCollision/Gimpact/gim_tri_collision.cpp \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.cpp \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btConvexCast.cpp \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.cpp \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.cpp \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.cpp \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btRaycastCallback.cpp \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.cpp \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.cpp \
    BulletPhysics/BulletDynamics/Character/btKinematicCharacterController.cpp \
    BulletPhysics/BulletDynamics/ConstraintSolver/btConeTwistConstraint.cpp \
    BulletPhysics/BulletDynamics/ConstraintSolver/btContactConstraint.cpp \
    BulletPhysics/BulletDynamics/ConstraintSolver/btGearConstraint.cpp \
    BulletPhysics/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.cpp \
    BulletPhysics/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.cpp \
    BulletPhysics/BulletDynamics/ConstraintSolver/btHinge2Constraint.cpp \
    BulletPhysics/BulletDynamics/ConstraintSolver/btHingeConstraint.cpp \
    BulletPhysics/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.cpp \
    BulletPhysics/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.cpp \
    BulletPhysics/BulletDynamics/ConstraintSolver/btSliderConstraint.cpp \
    BulletPhysics/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.cpp \
    BulletPhysics/BulletDynamics/ConstraintSolver/btTypedConstraint.cpp \
    BulletPhysics/BulletDynamics/ConstraintSolver/btUniversalConstraint.cpp \
    BulletPhysics/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp \
    BulletPhysics/BulletDynamics/Dynamics/btRigidBody.cpp \
    BulletPhysics/BulletDynamics/Dynamics/btSimpleDynamicsWorld.cpp \
    BulletPhysics/BulletDynamics/Dynamics/Bullet-C-API.cpp \
    BulletPhysics/BulletDynamics/Vehicle/btRaycastVehicle.cpp \
    BulletPhysics/BulletDynamics/Vehicle/btWheelInfo.cpp \
    BulletPhysics/BulletMultiThreaded/btGpu3DGridBroadphase.cpp \
    BulletPhysics/BulletMultiThreaded/btParallelConstraintSolver.cpp \
    BulletPhysics/BulletMultiThreaded/btThreadSupportInterface.cpp \
    BulletPhysics/BulletMultiThreaded/PosixThreadSupport.cpp \
    BulletPhysics/BulletMultiThreaded/SequentialThreadSupport.cpp \
    BulletPhysics/BulletMultiThreaded/SpuCollisionObjectWrapper.cpp \
    BulletPhysics/BulletMultiThreaded/SpuCollisionTaskProcess.cpp \
    BulletPhysics/BulletMultiThreaded/SpuContactManifoldCollisionAlgorithm.cpp \
    BulletPhysics/BulletMultiThreaded/SpuFakeDma.cpp \
    BulletPhysics/BulletMultiThreaded/SpuGatheringCollisionDispatcher.cpp \
    BulletPhysics/BulletMultiThreaded/SpuLibspe2Support.cpp \
    BulletPhysics/BulletMultiThreaded/SpuSampleTaskProcess.cpp \
    BulletPhysics/BulletMultiThreaded/Win32ThreadSupport.cpp \
    BulletPhysics/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/boxBoxDistance.cpp \
    BulletPhysics/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuCollisionShapes.cpp \
    BulletPhysics/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuContactResult.cpp \
    BulletPhysics/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuGatheringCollisionTask.cpp \
    BulletPhysics/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuMinkowskiPenetrationDepthSolver.cpp \
    BulletPhysics/BulletMultiThreaded/SpuSampleTask/SpuSampleTask.cpp \
    BulletPhysics/LinearMath/btAlignedAllocator.cpp \
    BulletPhysics/LinearMath/btConvexHull.cpp \
    BulletPhysics/LinearMath/btConvexHullComputer.cpp \
    BulletPhysics/LinearMath/btGeometryUtil.cpp \
    BulletPhysics/LinearMath/btPolarDecomposition.cpp \
    BulletPhysics/LinearMath/btQuickprof.cpp \
    BulletPhysics/LinearMath/btSerializer.cpp \
    BulletPhysics/LinearMath/btVector3.cpp

HEADERS += \
    physics/boundingbox.h \
    physics/boundingsphere.h \
    physics/collisionpointinfo.h \
    physics/dynamiccharacter.h \
    physics/dynamiccharacterwithcam.h \
    physics/physicengine.h \
    physics/physicenginemanager.h \
    physics/physicext.h \
    physics/physicobject.h \
    physics/physics.h \
    physics/responseobject.h \
    physics/trigger.h \
    physics/PhysicMath/eigenvector.h \
    physics/BulletPhysicEngine/bulletcollisiondispatcher.h \
    physics/BulletPhysicEngine/bulletdebugdrawer.h \
    physics/BulletPhysicEngine/bulletdiscretedynamicsworld.h \
    physics/BulletPhysicEngine/bulletdynamiccharacter.h \
    physics/BulletPhysicEngine/bulletdynamiccharacterwithcam.h \
    physics/BulletPhysicEngine/bulletparallelcollisioncallback.h \
    physics/BulletPhysicEngine/bulletphysicengine.h \
    physics/BulletPhysicEngine/bulletphysicmatrixtogeometry.h \
    physics/BulletPhysicEngine/bulletphysicobject.h \
    physics/BulletPhysicEngine/bulletspucollisiondispatcher.h \
    physics/igeometryaccess.h \
    physics/icameraaccess.h

HEADERS += BulletPhysics/BulletCollision/BroadphaseCollision/btAxisSweep3.h \
    BulletPhysics/BulletCollision/BroadphaseCollision/btBroadphaseInterface.h \
    BulletPhysics/BulletCollision/BroadphaseCollision/btBroadphaseProxy.h \
    BulletPhysics/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.h \
    BulletPhysics/BulletCollision/BroadphaseCollision/btDbvt.h \
    BulletPhysics/BulletCollision/BroadphaseCollision/btDbvtBroadphase.h \
    BulletPhysics/BulletCollision/BroadphaseCollision/btDispatcher.h \
    BulletPhysics/BulletCollision/BroadphaseCollision/btMultiSapBroadphase.h \
    BulletPhysics/BulletCollision/BroadphaseCollision/btOverlappingPairCache.h \
    BulletPhysics/BulletCollision/BroadphaseCollision/btOverlappingPairCallback.h \
    BulletPhysics/BulletCollision/BroadphaseCollision/btQuantizedBvh.h \
    BulletPhysics/BulletCollision/BroadphaseCollision/btSimpleBroadphase.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btBoxBoxDetector.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btCollisionConfiguration.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btCollisionCreateFunc.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btCollisionDispatcher.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btCollisionObject.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btCollisionObjectWrapper.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btCollisionWorld.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btGhostObject.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btInternalEdgeUtility.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btManifoldResult.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btSimulationIslandManager.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.h \
    BulletPhysics/BulletCollision/CollisionDispatch/btUnionFind.h \
    BulletPhysics/BulletCollision/CollisionDispatch/SphereTriangleDetector.h \
    BulletPhysics/BulletCollision/CollisionShapes/btBox2dShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btBoxShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btCapsuleShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btCollisionMargin.h \
    BulletPhysics/BulletCollision/CollisionShapes/btCollisionShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btCompoundShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btConcaveShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btConeShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btConvex2dShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btConvexHullShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btConvexInternalShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btConvexPointCloudShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btConvexPolyhedron.h \
    BulletPhysics/BulletCollision/CollisionShapes/btConvexShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btCylinderShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btEmptyShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btMaterial.h \
    BulletPhysics/BulletCollision/CollisionShapes/btMinkowskiSumShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btMultiSphereShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btOptimizedBvh.h \
    BulletPhysics/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btShapeHull.h \
    BulletPhysics/BulletCollision/CollisionShapes/btSphereShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btStaticPlaneShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btStridingMeshInterface.h \
    BulletPhysics/BulletCollision/CollisionShapes/btTetrahedronShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btTriangleBuffer.h \
    BulletPhysics/BulletCollision/CollisionShapes/btTriangleCallback.h \
    BulletPhysics/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.h \
    BulletPhysics/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.h \
    BulletPhysics/BulletCollision/CollisionShapes/btTriangleInfoMap.h \
    BulletPhysics/BulletCollision/CollisionShapes/btTriangleMesh.h \
    BulletPhysics/BulletCollision/CollisionShapes/btTriangleMeshShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btTriangleShape.h \
    BulletPhysics/BulletCollision/CollisionShapes/btUniformScalingShape.h \
    BulletPhysics/BulletCollision/Gimpact/btBoxCollision.h \
    BulletPhysics/BulletCollision/Gimpact/btClipPolygon.h \
    BulletPhysics/BulletCollision/Gimpact/btContactProcessing.h \
    BulletPhysics/BulletCollision/Gimpact/btGenericPoolAllocator.h \
    BulletPhysics/BulletCollision/Gimpact/btGeometryOperations.h \
    BulletPhysics/BulletCollision/Gimpact/btGImpactBvh.h \
    BulletPhysics/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.h \
    BulletPhysics/BulletCollision/Gimpact/btGImpactMassUtil.h \
    BulletPhysics/BulletCollision/Gimpact/btGImpactQuantizedBvh.h \
    BulletPhysics/BulletCollision/Gimpact/btGImpactShape.h \
    BulletPhysics/BulletCollision/Gimpact/btQuantization.h \
    BulletPhysics/BulletCollision/Gimpact/btTriangleShapeEx.h \
    BulletPhysics/BulletCollision/Gimpact/gim_array.h \
    BulletPhysics/BulletCollision/Gimpact/gim_basic_geometry_operations.h \
    BulletPhysics/BulletCollision/Gimpact/gim_bitset.h \
    BulletPhysics/BulletCollision/Gimpact/gim_box_collision.h \
    BulletPhysics/BulletCollision/Gimpact/gim_box_set.h \
    BulletPhysics/BulletCollision/Gimpact/gim_clip_polygon.h \
    BulletPhysics/BulletCollision/Gimpact/gim_contact.h \
    BulletPhysics/BulletCollision/Gimpact/gim_geom_types.h \
    BulletPhysics/BulletCollision/Gimpact/gim_geometry.h \
    BulletPhysics/BulletCollision/Gimpact/gim_hash_table.h \
    BulletPhysics/BulletCollision/Gimpact/gim_linear_math.h \
    BulletPhysics/BulletCollision/Gimpact/gim_math.h \
    BulletPhysics/BulletCollision/Gimpact/gim_memory.h \
    BulletPhysics/BulletCollision/Gimpact/gim_radixsort.h \
    BulletPhysics/BulletCollision/Gimpact/gim_tri_collision.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btConvexCast.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btConvexPenetrationDepthSolver.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btDiscreteCollisionDetectorInterface.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btGjkEpa2.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btManifoldPoint.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btPersistentManifold.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btPointCollector.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btRaycastCallback.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btSimplexSolverInterface.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.h \
    BulletPhysics/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.h \
    BulletPhysics/BulletDynamics/Character/btCharacterControllerInterface.h \
    BulletPhysics/BulletDynamics/Character/btKinematicCharacterController.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btConeTwistConstraint.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btConstraintSolver.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btContactConstraint.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btContactSolverInfo.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btGearConstraint.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btHinge2Constraint.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btHingeConstraint.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btJacobianEntry.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btSliderConstraint.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btSolverBody.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btSolverConstraint.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btTypedConstraint.h \
    BulletPhysics/BulletDynamics/ConstraintSolver/btUniversalConstraint.h \
    BulletPhysics/BulletDynamics/Dynamics/btActionInterface.h \
    BulletPhysics/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h \
    BulletPhysics/BulletDynamics/Dynamics/btDynamicsWorld.h \
    BulletPhysics/BulletDynamics/Dynamics/btRigidBody.h \
    BulletPhysics/BulletDynamics/Dynamics/btSimpleDynamicsWorld.h \
    BulletPhysics/BulletDynamics/Vehicle/btRaycastVehicle.h \
    BulletPhysics/BulletDynamics/Vehicle/btVehicleRaycaster.h \
    BulletPhysics/BulletDynamics/Vehicle/btWheelInfo.h \
    BulletPhysics/BulletMultiThreaded/btGpu3DGridBroadphase.h \
    BulletPhysics/BulletMultiThreaded/btGpu3DGridBroadphaseSharedCode.h \
    BulletPhysics/BulletMultiThreaded/btGpu3DGridBroadphaseSharedDefs.h \
    BulletPhysics/BulletMultiThreaded/btGpu3DGridBroadphaseSharedTypes.h \
    BulletPhysics/BulletMultiThreaded/btGpuDefines.h \
    BulletPhysics/BulletMultiThreaded/btGpuUtilsSharedCode.h \
    BulletPhysics/BulletMultiThreaded/btGpuUtilsSharedDefs.h \
    BulletPhysics/BulletMultiThreaded/btParallelConstraintSolver.h \
    BulletPhysics/BulletMultiThreaded/btThreadSupportInterface.h \
    BulletPhysics/BulletMultiThreaded/HeapManager.h \
    BulletPhysics/BulletMultiThreaded/PlatformDefinitions.h \
    BulletPhysics/BulletMultiThreaded/PosixThreadSupport.h \
    BulletPhysics/BulletMultiThreaded/PpuAddressSpace.h \
    BulletPhysics/BulletMultiThreaded/SequentialThreadSupport.h \
    BulletPhysics/BulletMultiThreaded/SpuCollisionObjectWrapper.h \
    BulletPhysics/BulletMultiThreaded/SpuCollisionTaskProcess.h \
    BulletPhysics/BulletMultiThreaded/SpuContactManifoldCollisionAlgorithm.h \
    BulletPhysics/BulletMultiThreaded/SpuDoubleBuffer.h \
    BulletPhysics/BulletMultiThreaded/SpuFakeDma.h \
    BulletPhysics/BulletMultiThreaded/SpuGatheringCollisionDispatcher.h \
    BulletPhysics/BulletMultiThreaded/SpuLibspe2Support.h \
    BulletPhysics/BulletMultiThreaded/SpuSampleTaskProcess.h \
    BulletPhysics/BulletMultiThreaded/SpuSync.h \
    BulletPhysics/BulletMultiThreaded/TrbDynBody.h \
    BulletPhysics/BulletMultiThreaded/TrbStateVec.h \
    BulletPhysics/BulletMultiThreaded/vectormath2bullet.h \
    BulletPhysics/BulletMultiThreaded/Win32ThreadSupport.h \
    BulletPhysics/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/Box.h \
    BulletPhysics/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/boxBoxDistance.h \
    BulletPhysics/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuCollisionShapes.h \
    BulletPhysics/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuContactResult.h \
    BulletPhysics/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuConvexPenetrationDepthSolver.h \
    BulletPhysics/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuGatheringCollisionTask.h \
    BulletPhysics/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuLocalSupport.h \
    BulletPhysics/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuMinkowskiPenetrationDepthSolver.h \
    BulletPhysics/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuPreferredPenetrationDirections.h \
    BulletPhysics/BulletMultiThreaded/SpuSampleTask/SpuSampleTask.h \
    BulletPhysics/LinearMath/btAabbUtil2.h \
    BulletPhysics/LinearMath/btAlignedAllocator.h \
    BulletPhysics/LinearMath/btAlignedObjectArray.h \
    BulletPhysics/LinearMath/btConvexHull.h \
    BulletPhysics/LinearMath/btConvexHullComputer.h \
    BulletPhysics/LinearMath/btDefaultMotionState.h \
    BulletPhysics/LinearMath/btGeometryUtil.h \
    BulletPhysics/LinearMath/btGrahamScan2dConvexHull.h \
    BulletPhysics/LinearMath/btHashMap.h \
    BulletPhysics/LinearMath/btIDebugDraw.h \
    BulletPhysics/LinearMath/btList.h \
    BulletPhysics/LinearMath/btMatrix3x3.h \
    BulletPhysics/LinearMath/btMinMax.h \
    BulletPhysics/LinearMath/btMotionState.h \
    BulletPhysics/LinearMath/btPolarDecomposition.h \
    BulletPhysics/LinearMath/btPoolAllocator.h \
    BulletPhysics/LinearMath/btQuadWord.h \
    BulletPhysics/LinearMath/btQuaternion.h \
    BulletPhysics/LinearMath/btQuickprof.h \
    BulletPhysics/LinearMath/btRandom.h \
    BulletPhysics/LinearMath/btScalar.h \
    BulletPhysics/LinearMath/btSerializer.h \
    BulletPhysics/LinearMath/btStackAlloc.h \
    BulletPhysics/LinearMath/btTransform.h \
    BulletPhysics/LinearMath/btTransformUtil.h \
    BulletPhysics/LinearMath/btVector3.h

#unix {
#    target.path = /usr/lib
#    INSTALLS += target
#}

#OTHER_FILES +=
